#ifndef ENUM_BUTTON_STATE
#define ENUM_BUTTON_STATE

enum ButtonState {
	BUTTON_MOUSE_OUT,       // 0 
	BUTTON_MOUSE_HOVER,     // 1
    BUTTON_MOUSELEFT_DOWN,  // 2
    BUTTON_MOUSERIGHT_DOWN, // 3
    BUTTON_MOUSELEFT_UP,    // 4
    BUTTON_MOUSERIGHT_UP    // 5
};

#endif